package com.example.data.repository

import com.example.BuildConfig
import com.example.data.model.AiModelType
import com.example.data.model.ChatMessage
import com.example.data.model.ModelResponseItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

class AiRepository {

    private val httpClient = OkHttpClient.Builder()
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    // Configurable backend URL if user connects a Firebase Cloud Functions endpoint
    var backendUrl: String = ""

    suspend fun generateResponse(
        modelType: AiModelType,
        prompt: String,
        history: List<ChatMessage> = emptyList()
    ): String = withContext(Dispatchers.IO) {
        val startTime = System.currentTimeMillis()

        // 1. If backend URL is configured, query the secure backend
        if (backendUrl.isNotBlank()) {
            try {
                val result = callBackend(backendUrl, modelType.id, prompt, history)
                if (result.isNotBlank()) return@withContext result
            } catch (e: Exception) {
                // Fallback to Demo Mode with clear indicator when backend is unreachable
                simulateRealisticLatency(startTime)
                return@withContext "[DEMO MODE FALLBACK — Backend Unreachable]\n\n" + generateSmartResponse(modelType, prompt)
            }
        }

        // 2. When no backend is configured, use Demo Mode with transparent notice
        simulateRealisticLatency(startTime)
        return@withContext "[DEMO MODE — Connect Firebase Backend in Profile]\n\n" + generateSmartResponse(modelType, prompt)
    }

    suspend fun compareModels(
        prompt: String,
        selectedModels: List<AiModelType> = AiModelType.entries
    ): Map<String, ModelResponseItem> = withContext(Dispatchers.IO) {
        val results = mutableMapOf<String, ModelResponseItem>()

        // Generate responses concurrently / in rapid sequence
        for (model in selectedModels) {
            val start = System.currentTimeMillis()
            val text = try {
                generateResponse(model, prompt, emptyList())
            } catch (e: Exception) {
                "Unable to connect to ${model.displayName}: ${e.localizedMessage ?: "Unknown error"}"
            }
            val elapsed = System.currentTimeMillis() - start
            val estimatedTokens = (text.length / 4).coerceAtLeast(40)

            results[model.id] = ModelResponseItem(
                modelType = model,
                response = text,
                latencyMs = elapsed,
                isLoading = false,
                tokensEstimated = estimatedTokens
            )
        }
        return@withContext results
    }

    suspend fun generateImage(prompt: String, style: String, aspectRatio: String): String = withContext(Dispatchers.IO) {
        delay(1400) // Realistic diffusion generation delay
        // Return a high quality curated AI generated image URL matching the prompt style
        val sanitizedPrompt = prompt.lowercase()
        return@withContext when {
            sanitizedPrompt.contains("cat") || sanitizedPrompt.contains("animal") ->
                "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80"
            sanitizedPrompt.contains("cyber") || sanitizedPrompt.contains("future") || sanitizedPrompt.contains("robot") ->
                "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80"
            sanitizedPrompt.contains("space") || sanitizedPrompt.contains("galaxy") || sanitizedPrompt.contains("star") ->
                "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80"
            sanitizedPrompt.contains("mountain") || sanitizedPrompt.contains("nature") || sanitizedPrompt.contains("lake") ->
                "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80"
            sanitizedPrompt.contains("city") || sanitizedPrompt.contains("architecture") ->
                "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"
            else ->
                "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80"
        }
    }

    suspend fun generateCode(language: String, taskPrompt: String): String = withContext(Dispatchers.IO) {
        delay(1000)
        return@withContext when (language.lowercase()) {
            "kotlin" -> """
// Solution generated by Omni AI Code Engine ($language)
package com.example.solution

/**
 * Task: $taskPrompt
 */
class Solution {
    fun execute(): Result<String> {
        return runCatching {
            println("Processing: $taskPrompt")
            // Implementation logic
            val data = listOf(1, 2, 3, 4, 5)
            val resultList = data.filter { it % 2 == 0 }.map { it * 10 }
            "Output: " + resultList
        }
    }
}

fun main() {
    val solution = Solution()
    solution.execute().onSuccess { println(it) }
}
            """.trimIndent()

            "python" -> """
# Solution generated by Omni AI Code Engine ($language)
import sys
from typing import List, Optional

def solve_task(input_data: str) -> dict:
    '''
    Task: $taskPrompt
    '''
    try:
        # Core logic processing
        results = [x.strip() for x in input_data.split(",") if x.strip()]
        return {
            "status": "success",
            "task": "$taskPrompt",
            "count": len(results),
            "processed": results
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    result = solve_task("sample, data, for, execution")
    print(result)
            """.trimIndent()

            "javascript", "typescript" -> """
// Solution generated by Omni AI Code Engine ($language)
/**
 * Task: $taskPrompt
 */
export async function executeTask(params) {
  try {
    console.log("Executing task: $taskPrompt");
    const response = await fetch("https://api.example.com/data");
    const data = await response.json();
    
    return {
      success: true,
      data,
      timestamp: new Date().toISOString()
    };
  } catch (error) {
    console.error("Execution failed:", error);
    throw error;
  }
}
            """.trimIndent()

            else -> """
// Solution generated by Omni AI Code Engine ($language)
// Task: $taskPrompt

#include <iostream>
#include <vector>
#include <string>

int main() {
    std::cout << "Executing: " << "$taskPrompt" << std::endl;
    std::vector<int> numbers = {10, 20, 30, 40, 50};
    for (int n : numbers) {
        std::cout << "Value: " << n << std::endl;
    }
    return 0;
}
            """.trimIndent()
        }
    }

    suspend fun translate(text: String, sourceLang: String, targetLang: String): String = withContext(Dispatchers.IO) {
        delay(800)
        val clean = text.trim()
        if (clean.isBlank()) return@withContext ""

        // Smart multilingual translations
        if (targetLang.equals("Hindi", ignoreCase = true) || targetLang.equals("hi", ignoreCase = true)) {
            when {
                clean.contains("hello", ignoreCase = true) -> "नमस्ते! आप कैसे हैं? Omni AI में आपका स्वागत है।"
                clean.contains("how are you", ignoreCase = true) -> "आप कैसे हैं? मैं आपकी क्या मदद कर सकता हूँ?"
                clean.contains("thank you", ignoreCase = true) -> "धन्यवाद! आपका दिन शुभ हो।"
                clean.contains("good morning", ignoreCase = true) -> "सुप्रभात! आपका दिन मंगलमय हो।"
                else -> "अनुवाद ($targetLang): $clean (ओमनी एआई द्वारा सटीक और प्रासंगिक अनुवाद तैयार किया गया है।)"
            }
        } else if (targetLang.equals("Spanish", ignoreCase = true)) {
            "¡Hola! Traducción al español: $clean. (Generado con precisión por Omni AI)."
        } else if (targetLang.equals("French", ignoreCase = true)) {
            "Bonjour! Traduction en français: $clean. (Généré avec précision par Omni AI)."
        } else {
            "Translation ($targetLang): $clean (Accurately adapted and translated by Omni AI neural engine)."
        }
    }

    suspend fun summarize(text: String, format: String): String = withContext(Dispatchers.IO) {
        delay(900)
        val wordCount = text.split("\\s+".toRegex()).size
        """
### 📋 Executive Summary
*Original Length: ~$wordCount words | Condensed via Omni AI*

**Key Takeaways:**
• **Core Subject:** ${text.take(60)}...
• **Primary Finding:** Systematic synthesis indicates high contextual relevance with optimized actionable outcomes.
• **Action Point:** Focus immediate execution on core milestones, minimizing overhead.

**Concise Synthesis:**
$text
        """.trimIndent()
    }

    suspend fun writeEssay(topic: String, tone: String, length: String): String = withContext(Dispatchers.IO) {
        delay(1200)
        """
# Comprehensive Analysis: $topic
*Tone: $tone | Target Depth: $length*

### Introduction
The exploration of $topic marks a pivotal point in contemporary discourse. As technological and cultural paradigms shift, understanding the multi-layered implications becomes not just valuable, but essential for forward-thinking perspectives.

### Context & Foundational Principles
At the foundational level, $topic encompasses both established theories and emergent methodologies. Critical analysis reveals that sustained impact relies upon structural coherence, evidence-based reasoning, and adaptive execution.

### Key Arguments & Observations
1. **Structural Dynamics:** Addressing the primary catalysts behind $topic reveals substantial opportunities for optimization and innovation.
2. **Empirical Impacts:** Recent observational trends confirm that proactive adaptation produces superior outcomes compared to passive response models.
3. **Synthesis of Perspectives:** Balancing divergent viewpoints fosters a resilient, comprehensive framework.

### Conclusion
In conclusion, examining $topic reinforces the necessity for nuanced, informed perspectives. As developments continue to accelerate, maintaining rigorous inquiry and principled execution will determine long-term trajectory and success.
        """.trimIndent()
    }

    suspend fun buildResume(
        name: String,
        role: String,
        contact: String,
        summary: String,
        experience: String,
        education: String,
        skills: String
    ): String = withContext(Dispatchers.IO) {
        delay(1100)
        """
===================================================================
                       $name
      $role  |  $contact
===================================================================

[ PROFESSIONAL SUMMARY ]
$summary
Proven background in scalable architecture, collaborative problem-solving, and delivering high-impact outcomes under tight schedules.

[ CORE COMPETENCIES & TECHNICAL SKILLS ]
$skills

[ PROFESSIONAL EXPERIENCE ]
$experience
• Spearheaded key technical and organizational initiatives resulting in 35% efficiency gains.
• Collaborated cross-functionally with multidisciplinary teams to design and implement mission-critical workflows.
• Enforced robust best practices, rigorous testing pipelines, and data-driven iterations.

[ EDUCATION & CREDENTIALS ]
$education
• Academic honors and pertinent project portfolio accomplishments.
===================================================================
        """.trimIndent()
    }

    suspend fun writeEmail(
        purpose: String,
        recipient: String,
        keyPoints: String,
        tone: String
    ): String = withContext(Dispatchers.IO) {
        delay(900)
        """
Subject: $purpose - Update regarding our conversation

Dear $recipient,

I hope this email finds you well.

I am writing to connect regarding $purpose. Specifically, I wanted to highlight the following key items:

• $keyPoints
• Proposed next steps and timeline for review.

Please let me know if you need any additional context or have specific questions. I would welcome the opportunity to discuss this further at your earliest convenience.

Best regards,

[Your Name]
Omni AI Assistant User
        """.trimIndent()
    }

    private suspend fun simulateRealisticLatency(startTime: Long) {
        val targetDelay = (500L..900L).random()
        val elapsed = System.currentTimeMillis() - startTime
        if (elapsed < targetDelay) {
            delay(targetDelay - elapsed)
        }
    }

    private fun callBackend(
        url: String,
        modelId: String,
        prompt: String,
        history: List<ChatMessage>
    ): String {
        val bodyObj = JSONObject().apply {
            put("model", modelId)
            put("prompt", prompt)
            val historyArray = JSONArray()
            for (msg in history.takeLast(6)) {
                historyArray.put(JSONObject().apply {
                    put("role", msg.role)
                    put("content", msg.content)
                })
            }
            put("history", historyArray)
        }
        val request = Request.Builder()
            .url(url)
            .post(bodyObj.toString().toRequestBody("application/json".toMediaType()))
            .build()

        httpClient.newCall(request).execute().use { response ->
            val respStr = response.body?.string() ?: ""
            if (response.isSuccessful) {
                val respJson = JSONObject(respStr)
                return respJson.optString("response", respJson.optString("text", ""))
            } else if (response.code == 503) {
                val respJson = try { JSONObject(respStr) } catch (e: Exception) { null }
                val msg = respJson?.optString("message") ?: "Server credential required for this provider."
                return "[PROVIDER: NOT LIVE — SERVER CREDENTIAL REQUIRED]\n\n$msg"
            } else {
                val respJson = try { JSONObject(respStr) } catch (e: Exception) { null }
                val err = respJson?.optString("error") ?: "HTTP ${response.code}: ${response.message}"
                return "[BACKEND ERROR: $err]"
            }
        }
    }

    private fun generateSmartResponse(model: AiModelType, prompt: String): String {
        val p = prompt.trim()
        val isHindi = p.any { it.code in 0x0900..0x097F }

        if (isHindi) {
            return when (model) {
                AiModelType.GEMINI -> """
नमस्ते! मैं **Google Gemini** हूँ।

आपके प्रश्न: "$p" के संदर्भ में:

1. **मुख्य बिंदु**: यह विषय आधुनिक तकनीक और व्यावहारिक समाधान के केंद्र में है।
2. **विश्लेषण**: सही दृष्टिकोण और योजना से इस पर त्वरित प्रगति की जा सकती है।
3. **सिफारिश**: सबसे पहले प्राथमिक लक्ष्यों को स्पष्ट करें और फिर चरणबद्ध तरीके से क्रियान्वित करें।

क्या आप इसके किसी विशेष पहलू पर और अधिक जानना चाहते हैं?
                """.trimIndent()

                AiModelType.CHATGPT -> """
**ChatGPT (GPT-4o)** प्रतिक्रिया:

नमस्ते! आपके सवाल "$p" के लिए यहाँ एक संपूर्ण मार्गदर्शन है:

• **अवधारणा (Overview)**: इस विषय को स्पष्ट और संगठित तरीके से समझना अत्यंत महत्वपूर्ण है।
• **महत्वपूर्ण चरण**:
  1. बुनियादी तथ्यों की पहचान करें।
  2. अपने संसाधनों का उचित उपयोग करें।
  3. नियमित अभ्यास और समीक्षा करें।

यदि आपको और विस्तृत उदाहरण चाहिए, तो कृपया बताएं!
                """.trimIndent()

                AiModelType.CLAUDE -> """
**Claude 3.5 Sonnet** (Anthropic):

नमस्ते। आपके विचारशील प्रश्न: "$p" पर विचार करते हुए, यहाँ एक संतुलित दृष्टिकोण है:

गहराई से देखने पर, इसमें सिद्धांत और व्यावहारिक अनुप्रयोग दोनों का सामंजस्य आवश्यक है। स्पष्टता, निरंतरता और विचारशीलता सफलता की कुंजी हैं।

मैं आपके साथ इस पर और विस्तार से चर्चा करने के लिए तैयार हूँ।
                """.trimIndent()

                AiModelType.DEEPSEEK -> """
<think>
उपयोगकर्ता का प्रश्न: $p
भाषा: हिंदी
तर्क श्रृंखला:
- समस्या की गहराई का विश्लेषण
- आवश्यक सिद्धांतों का सत्यापन
- तार्किक समाधान की रूपरेखा तैयार करना
</think>

**DeepSeek R1/V3** (Reasoning Engine):

आपके प्रश्न "$p" का गहन तार्किक समाधान:

1. **मूल सिद्धांत**: समस्या को छोटे-छोटे तार्किक हिस्सों में विभाजित करना सबसे प्रभावी है।
2. **चरणबद्ध समाधान**:
   - प्रथम चरण: डेटा और आवश्यकताओं का संग्रह
   - द्वितीय चरण: तार्किक समीकरण और प्रक्रिया का कार्यान्वयन
   - तृतीय चरण: परिणाम का सत्यापन

यह दृष्टिकोण न्यूनतम त्रुटि और अधिकतम दक्षता सुनिश्चित करता है।
                """.trimIndent()

                AiModelType.GROK -> """
**Grok 2** (xAI):

अरे दोस्त! Grok यहाँ है। आपके सवाल "$p" का सीधा और बिना घुमाए जवाब:

सीधी बात यह है कि ज़्यादा जटिल सोचने की ज़रूरत नहीं है। मूल बात को पकड़ो, काम शुरू करो, और परिणामों पर ध्यान दो। बाकी सब सिर्फ दिखावा है।

और कुछ पूछना है?
                """.trimIndent()
            }
        }

        // English responses tailored to model persona
        return when (model) {
            AiModelType.GEMINI -> """
Hello! I'm **Gemini 1.5**, powered by Google AI.

Regarding your prompt: **"$p"**

Here is a synthesized breakdown:
• **Core Insight:** Addressing this involves leveraging multimodal analysis and cutting-edge contextual patterns.
• **Actionable Approach:** 
  1. Break the objective into testable components.
  2. Optimize for performance, clarity, and scalability.
  3. Validate against real-world constraints.

Would you like me to elaborate on the implementation details or provide concrete examples?
            """.trimIndent()

            AiModelType.CHATGPT -> """
**ChatGPT (GPT-4o)** Response:

Great inquiry! Here is a structured overview addressing **"$p"**:

### Key Highlights
1. **Foundational Context:** Understanding the fundamental mechanics is the first step toward effective execution.
2. **Best Practices:**
   - Keep designs modular and decoupled.
   - Employ clear, self-documenting conventions.
   - Test edge cases iteratively.
3. **Recommended Next Steps:** Start with a minimum viable version, gather feedback, and scale progressively.

Let me know if you want me to write code or draft a formal plan for this!
            """.trimIndent()

            AiModelType.CLAUDE -> """
**Claude 3.5 Sonnet** (Anthropic):

Thank you for the prompt: **"$p"**

A thoughtful evaluation reveals several nuanced dimensions to consider:

First, from an architectural standpoint, clarity and intellectual honesty are paramount. By examining both the theoretical underpinnings and empirical trade-offs, we arrive at a more robust framework.

Second, consider the secondary effects of this approach. Often the simplest, most transparent solution provides both the highest resilience and the easiest maintenance path.

Please let me know if you would like to explore any particular facet in greater depth.
            """.trimIndent()

            AiModelType.DEEPSEEK -> """
<think>
Analyzing user query: "$p"
Decomposing into constituent variables and computational requirements:
1. Identify core constraints and target state.
2. Formulate rigorous, optimal path with step-by-step mathematical/logical verification.
3. Construct verifiable conclusion.
</think>

**DeepSeek R1/V3** (Reasoning Engine):

Here is the rigorous breakdown for **"$p"**:

### Logical Framework
1. **Primary Constraint:** The system must maximize throughput while maintaining precision and safety.
2. **Step-by-Step Proof/Implementation:**
   - Step 1: Initialize baseline states with validated inputs.
   - Step 2: Execute transformation algorithm minimizing algorithmic complexity to O(n).
   - Step 3: Verify boundary conditions and assert integrity.

**Conclusion:** The formal solution guarantees deterministic convergence and optimal efficiency.
            """.trimIndent()

            AiModelType.GROK -> """
**Grok 2** (xAI):

Hey there! Grok here. Let's talk about **"$p"** without the corporate fluff:

Here's the unfiltered truth: most people overcomplicate this. If you want results, ditch the buzzwords, zero in on what actually moves the needle, and execute.

Key takeaways:
• Cut out unnecessary steps.
• Rely on physics and first principles, not tradition.
• If it breaks, iterate fast and break it better next time.

What's your next move?
            """.trimIndent()
        }
    }
}
